### ISSUE TITLE
Template error on Bootstrap to Tailwind Converter

### ISSUE THREAD

**Issue by halans** [horizon-ui/horizon-ai-template-pro#2]
When trying to access Bootstrap to Tailwind Converter, I am getting an error.

![CleanShot 2023-11-25 at 15 39 37@2x](https://github.com/horizon-ui/horizon-ai-template-pro/assets/21991/c39bf869-bc25-431e-bd9a-3fdbdd06401e)

![CleanShot 2023-11-25 at 15 38 33@2x](https://github.com/horizon-ui/horizon-ai-template-pro/assets/21991/e5f9d6ec-1d2c-49a7-aa3d-74c8aeb04077)

![CleanShot 2023-11-25 at 15 39 12@2x](https://github.com/horizon-ui/horizon-ai-template-pro/assets/21991/6aab534b-e93b-48a7-9123-48a19f7903dd)

![CleanShot 2023-11-25 at 15 50 51@2x](https://github.com/horizon-ui/horizon-ai-template-pro/assets/21991/4380595e-cb48-4d60-9fbe-60476c411fb8)

This is on JS version.

**Comment by halans** [comment]
As `npm run build` was failing, I noticed one TS issue (see other ticket).

Once I got past that, it continued but failed on
```
> Build error occurred
Error: Export encountered errors on following paths:
        /bootstrap-to-tailwind-converter
        /pet-name-generator
```

So, try running `npm run build` to find the error?

**Comment by halans** [comment]
info  - Creating an optimized production build .ReferenceError: string is not defined
    at CodeBlock (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/.next/server/pages/bootstrap-to-tailwind-converter.js:301:83)
    at Wc (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
    at Z (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)

Error occurred prerendering page "/bootstrap-to-tailwind-converter". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: string is not defined
    at CodeBlock (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/.next/server/pages/bootstrap-to-tailwind-converter.js:301:83)
    at Wc (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
    at Z (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
ReferenceError: string is not defined
    at Home (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/.next/server/pages/pet-name-generator.js:35:75)
    at Wc (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
    at Z (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)

**Comment by halans** [comment]
`const [copyText, setCopyText] = react__WEBPACK_IMPORTED_MODULE_5__.useState < string > "Copy";`

which in CodeBlock.jsx is

`  const [copyText, setCopyText] = useState < string > 'Copy';`


Which should be in JavaScript

`const [copyText, setCopyText] = useState('Copy');`

**Comment by simmmpleweb** [comment]
Fixed. Explained [here](https://github.com/horizon-ui/horizon-ai-template-pro/issues/7).
