### ISSUE TITLE
Accessing Pet Name Generator throws error

### ISSUE THREAD

**Issue by halans** [horizon-ui/horizon-ai-template-pro#4]
When trying to access Pet Name Generator, an error is thrown

![CleanShot 2023-11-25 at 15 48 32@2x](https://github.com/horizon-ui/horizon-ai-template-pro/assets/21991/e36d0ae8-1a27-4b2d-a8b0-68e0f611e5dc)

![CleanShot 2023-11-25 at 15 49 22@2x](https://github.com/horizon-ui/horizon-ai-template-pro/assets/21991/35815590-417c-4aed-a43d-b3a4f7a33490)

I am using the JS version.

**Comment by halans** [comment]
As `npm run build` was failing, I noticed one TS issue (see other ticket).

Once I got past that, it continued but failed on
```
> Build error occurred
Error: Export encountered errors on following paths:
        /bootstrap-to-tailwind-converter
        /pet-name-generator
```

So, try running `npm run build` to find the error?

**Comment by halans** [comment]
Error occurred prerendering page "/pet-name-generator". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: string is not defined
    at Home (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/.next/server/pages/pet-name-generator.js:35:75)
    at Wc (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
    at Z (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/halans/Development/GitHub/chatgpt-ai-template-js-pro-main/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)

**Comment by halans** [comment]
`const [type, setType] = react__WEBPACK_IMPORTED_MODULE_3__.useState < string > "";`

which is generated from :

`const [type, setType] = useState < string > '';`

which should be in JavaScript

`const [type, setType] = useState('');`

**Comment by simmmpleweb** [comment]
Fixed. Explained [here](https://github.com/horizon-ui/horizon-ai-template-pro/issues/7).
